version: '3'
services:
  postgresdb:
    image: postgres
    restart: always
    container_name: droptoken-db-cont
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: droptoken-password
      POSTGRES_DB: droptoken-db
    ports:
      - 5432:5432
    networks:
      - droptoken-ntw

  # nginx:
  #   image: nginx
  #   container_name: nginx
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - "8080:8080"
  #     - "443:443"
  #   networks:
  #     - droptoken-ntw

  9dt-backend:
    image: java:8-jre
    container_name: droptoken-backend
    volumes:
      - ./target/9dt-backend-1.0-SNAPSHOT.jar:/microservice/9dt-backend-1.0-SNAPSHOT.jar
      - ./src/main/resources/local.yml:/microservice/local.yml
    working_dir: /microservice
    command: ["java", "-jar", "9dt-backend-1.0-SNAPSHOT.jar", "server", "local.yml"]
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - droptoken-ntw

networks:
  droptoken-ntw:
    external:
      name: droptoken-ntw